server:
  port: 8081
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchenge:
        producer: ex.producer.sankhya
      routing-key:
        producer: rk.producer.sankhya
      dead-letter:
        producer: dl.producer.sankhya
